### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by hcltech84** [hcltech84/tutorial-developing-a-restful-api-with-go-and-gin#1]
- [x] Design API endpoints | [Wiki page](https://github.com/hcltech84/tutorial-developing-a-restful-api-with-go-and-gin/wiki/01-%E2%80%90-Design-API-endpoints)
- [x] #2 | [Wiki page](https://github.com/hcltech84/tutorial-developing-a-restful-api-with-go-and-gin/wiki/02-%E2%80%90-Initialize-a-Go-module)
- [x] #3 
- [x] #4 | [Wiki page](https://github.com/hcltech84/tutorial-developing-a-restful-api-with-go-and-gin/wiki/04-%E2%80%90--Write-a-handler-to-return-all-items)
- [x] #5 | [Wiki page](https://github.com/hcltech84/tutorial-developing-a-restful-api-with-go-and-gin/wiki/05-%E2%80%90--Write-a-handler-to-add-a-new-item)
- [x] #6 

# RC
- [x] #7
